"""empty message

Revision ID: 15e08482f8d
Revises: 1bc6b9c7cf8
Create Date: 2015-05-07 22:15:50.375551

"""

# revision identifiers, used by Alembic.
revision = '15e08482f8d'
down_revision = '1bc6b9c7cf8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_jobs', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_jobs', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
