"""empty message

Revision ID: 1997e721d51
Revises: 15e08482f8d
Create Date: 2015-05-07 22:38:09.512704

"""

# revision identifiers, used by Alembic.
revision = '1997e721d51'
down_revision = '15e08482f8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
