"""empty message

Revision ID: 1bc6b9c7cf8
Revises: None
Create Date: 2015-05-07 22:08:44.423022

"""

# revision identifiers, used by Alembic.
revision = '1bc6b9c7cf8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ff_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_p', sa.Float(), nullable=False),
    sa.Column('k_1', sa.Float(), nullable=False),
    sa.Column('tau_1', sa.Float(), nullable=False),
    sa.Column('k_2', sa.Float(), nullable=False),
    sa.Column('tau_2', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gc_metrics_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('train_at_limits', sa.Boolean(), nullable=False),
    sa.Column('with_power_meter', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_jobs')
    op.drop_table('gc_metrics_files')
    op.drop_table('ff_parameters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
