"""empty message

Revision ID: 2a425ea7d49
Revises: f6530bd6fb
Create Date: 2015-07-01 17:59:14.137720

"""

# revision identifiers, used by Alembic.
revision = '2a425ea7d49'
down_revision = 'f6530bd6fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'size')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'birth_year')
    ### end Alembic commands ###
