"""empty message

Revision ID: 2b23b1b67e8
Revises: b45336bc6d
Create Date: 2015-06-16 23:31:17.793085

"""

# revision identifiers, used by Alembic.
revision = '2b23b1b67e8'
down_revision = 'b45336bc6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_plans', sa.Column('load_metric', sa.String(length=128), nullable=False))
    op.add_column('ff_plans', sa.Column('perf_metric', sa.String(length=128), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ff_plans', 'perf_metric')
    op.drop_column('ff_plans', 'load_metric')
    ### end Alembic commands ###
