"""empty message

Revision ID: 3274be3cbb8
Revises: 1997e721d51
Create Date: 2015-05-07 22:48:28.068170

"""

# revision identifiers, used by Alembic.
revision = '3274be3cbb8'
down_revision = '1997e721d51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
