"""empty message

Revision ID: 37df8167bdf
Revises: 433b33ebd59
Create Date: 2015-06-25 16:32:14.894222

"""

# revision identifiers, used by Alembic.
revision = '37df8167bdf'
down_revision = '433b33ebd59'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pp_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strainpot', sa.Float(), nullable=False),
    sa.Column('responsepot', sa.Float(), nullable=False),
    sa.Column('perfpot', sa.Float(), nullable=False),
    sa.Column('straindelay', sa.Float(), nullable=False),
    sa.Column('responsedelay', sa.Float(), nullable=False),
    sa.Column('overflowdelay', sa.Float(), nullable=False),
    sa.Column('plan_scale_factor', sa.Float(), nullable=False),
    sa.Column('perf_scale_factor', sa.Float(), nullable=False),
    sa.Column('load_metric', sa.String(length=128), nullable=False),
    sa.Column('perf_metric', sa.String(length=128), nullable=False),
    sa.Column('plan_since_initial_pp', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pp_parameters')
    ### end Alembic commands ###
