"""empty message

Revision ID: 42d2e9e3ba6
Revises: 2e9db6b5c38
Create Date: 2015-07-23 12:56:12.706439

"""

# revision identifiers, used by Alembic.
revision = '42d2e9e3ba6'
down_revision = '2e9db6b5c38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gc_metrics_files', sa.Column('train_weekly_at_limits', sa.Boolean(), nullable=False))
    op.drop_column('gc_metrics_files', 'train_at_limits')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gc_metrics_files', sa.Column('train_at_limits', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('gc_metrics_files', 'train_weekly_at_limits')
    ### end Alembic commands ###
