"""empty message

Revision ID: 433b33ebd59
Revises: 2b23b1b67e8
Create Date: 2015-06-16 23:41:37.377933

"""

# revision identifiers, used by Alembic.
revision = '433b33ebd59'
down_revision = '2b23b1b67e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_parameters', sa.Column('load_metric', sa.String(length=128), nullable=False))
    op.add_column('ff_parameters', sa.Column('perf_metric', sa.String(length=128), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ff_parameters', 'perf_metric')
    op.drop_column('ff_parameters', 'load_metric')
    ### end Alembic commands ###
