"""empty message

Revision ID: 768b490192
Revises: 14b39a4b7eb
Create Date: 2015-05-08 13:37:28.746334

"""

# revision identifiers, used by Alembic.
revision = '768b490192'
down_revision = '14b39a4b7eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_jobs', sa.Column('_job_type', sa.Integer(), nullable=False))
    op.drop_column('pending_jobs', 'job_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_jobs', sa.Column('job_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pending_jobs', '_job_type')
    ### end Alembic commands ###
