"""empty message

Revision ID: ad2c15555b
Revises: 25da865a72b
Create Date: 2015-07-02 22:59:40.814697

"""

# revision identifiers, used by Alembic.
revision = 'ad2c15555b'
down_revision = '25da865a72b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pp_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_perf', sa.Float(), nullable=False),
    sa.Column('end_perf', sa.Float(), nullable=False),
    sa.Column('loads', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('strainpot', sa.Float(), nullable=False),
    sa.Column('responsepot', sa.Float(), nullable=False),
    sa.Column('perfpot', sa.Float(), nullable=False),
    sa.Column('straindelay', sa.Float(), nullable=False),
    sa.Column('responsedelay', sa.Float(), nullable=False),
    sa.Column('overflowdelay', sa.Float(), nullable=False),
    sa.Column('load_scale_factor', sa.Float(), nullable=False),
    sa.Column('perf_scale_factor', sa.Float(), nullable=False),
    sa.Column('load_metric', sa.String(length=128), nullable=False),
    sa.Column('perf_metric', sa.String(length=128), nullable=False),
    sa.Column('prequel_plan', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('goal', sa.Float(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('max_load', sa.Float(), nullable=False),
    sa.Column('off_weeks', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('off_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('weekly_cycle', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pp_plans')
    ### end Alembic commands ###
