"""empty message

Revision ID: bf1e3b437d
Revises: 42d2e9e3ba6
Create Date: 2015-08-02 12:56:53.761473

"""

# revision identifiers, used by Alembic.
revision = 'bf1e3b437d'
down_revision = '42d2e9e3ba6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_plans', sa.Column('min_load', sa.Float(), nullable=True))
    op.add_column('pp_plans', sa.Column('min_load', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pp_plans', 'min_load')
    op.drop_column('ff_plans', 'min_load')
    ### end Alembic commands ###
