"""empty message

Revision ID: f6530bd6fb
Revises: 37df8167bdf
Create Date: 2015-07-01 09:26:19.380139

"""

# revision identifiers, used by Alembic.
revision = 'f6530bd6fb'
down_revision = '37df8167bdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_legalese', sa.Boolean(), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'accept_legalese')
    ### end Alembic commands ###
